name: "XMTP Test Cleanup"
description: "Handles notifications and artifact uploads for XMTP tests"

inputs:
  test-name:
    description: "Name of the test for notifications and artifact naming"
    required: true
  environment:
    description: "Test environment (dev, production, etc.)"
    required: true
  retention-days:
    description: "Number of days to retain artifacts"
    required: false
    default: "90"
  save-to-cache:
    description: "Whether to save .data and .env back to cache after processing"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Upload logs and environment
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.environment }}-${{ inputs.test-name }}-logs
        path: |
          logs/**/*
          .env
        if-no-files-found: ignore
        overwrite: true
        include-hidden-files: true
        retention-days: ${{ inputs.retention-days }}

    - name: Upload installation databases
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.environment }}-${{ inputs.test-name }}-dbs
        path: |
          .data/**/*
        if-no-files-found: ignore
        overwrite: true
        include-hidden-files: true
        retention-days: ${{ inputs.retention-days }}

    - name: Save processed data to cache
      if: ${{ always() && inputs.save-to-cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          .data
          .env
        key: installation-${{ hashFiles('yarn.lock') }}
