FROM node:16

WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./
RUN yarn install

# Copy the rest of the code
COPY . .

# Set the environment variables
ENV XMTP_ENV=production
ENV GEOLOCATION=us-east

# Run the test
CMD ["yarn", "test", "ts_performance"]
