#!/bin/bash

XMTP_ENV="local"

# Matrix params
GROUP_COUNTS=(2 5)
PARALLEL_OPS_LIST=(1 5)
CHAOS_LATENCY_MS_LIST=(0 100)
CHAOS_JITTER_MS_LIST=(0 50)
CHAOS_PACKET_LOSS_PCT_LIST=(0 5)
CHAOS_EGRESS_LATENCY_MS_LIST=(0 100)
CHAOS_EGRESS_JITTER_MS_LIST=(0 50)
CHAOS_EGRESS_PACKET_LOSS_PCT_LIST=(0 5)
INSTALLATION_COUNTS=(3 5)
WORKER_COUNTS=(10 20)
RANDOM_INBOX_IDS_LIST=(30 50)
TARGET_EPOCHS=(50 100)

for GROUP_COUNT in "${GROUP_COUNTS[@]}"; do
for PARALLEL_OPS in "${PARALLEL_OPS_LIST[@]}"; do
for CHAOS_LATENCY_MS in "${CHAOS_LATENCY_MS_LIST[@]}"; do
for CHAOS_JITTER_MS in "${CHAOS_JITTER_MS_LIST[@]}"; do
for CHAOS_PACKET_LOSS_PCT in "${CHAOS_PACKET_LOSS_PCT_LIST[@]}"; do
for CHAOS_EGRESS_LATENCY_MS in "${CHAOS_EGRESS_LATENCY_MS_LIST[@]}"; do
for CHAOS_EGRESS_JITTER_MS in "${CHAOS_EGRESS_JITTER_MS_LIST[@]}"; do
for CHAOS_EGRESS_PACKET_LOSS_PCT in "${CHAOS_EGRESS_PACKET_LOSS_PCT_LIST[@]}"; do
for INSTALLATION_COUNT in "${INSTALLATION_COUNTS[@]}"; do
for WORKER_COUNT in "${WORKER_COUNTS[@]}"; do
for RANDOM_INBOX_IDS in "${RANDOM_INBOX_IDS_LIST[@]}"; do
for TARGET_EPOCH in "${TARGET_EPOCHS[@]}"; do

  echo ""
  echo "========================================================="
  echo "Running matrix config:"
  echo "GROUP_COUNT=$GROUP_COUNT"
  echo "PARALLEL_OPS=$PARALLEL_OPS"
  echo "CHAOS_LATENCY_MS=$CHAOS_LATENCY_MS"
  echo "CHAOS_JITTER_MS=$CHAOS_JITTER_MS"
  echo "CHAOS_PACKET_LOSS_PCT=$CHAOS_PACKET_LOSS_PCT"
  echo "CHAOS_EGRESS_LATENCY_MS=$CHAOS_EGRESS_LATENCY_MS"
  echo "CHAOS_EGRESS_JITTER_MS=$CHAOS_EGRESS_JITTER_MS"
  echo "CHAOS_EGRESS_PACKET_LOSS_PCT=$CHAOS_EGRESS_PACKET_LOSS_PCT"
  echo "INSTALLATION_COUNT=$INSTALLATION_COUNT"
  echo "WORKER_COUNT=$WORKER_COUNT"
  echo "RANDOM_INBOX_IDS=$RANDOM_INBOX_IDS"
  echo "TARGET_EPOCH=$TARGET_EPOCH"
  echo "XMTP_ENV=$XMTP_ENV"
  echo "========================================================="

  export GROUP_COUNT
  export PARALLEL_OPS
  export CHAOS_LATENCY_MS
  export CHAOS_JITTER_MS
  export CHAOS_PACKET_LOSS_PCT
  export CHAOS_EGRESS_LATENCY_MS
  export CHAOS_EGRESS_JITTER_MS
  export CHAOS_EGRESS_PACKET_LOSS_PCT
  export INSTALLATION_COUNT
  export WORKER_COUNT
  export RANDOM_INBOX_IDS
  export TARGET_EPOCH
  export XMTP_ENV

  # Kick off the tests
  yarn run:commitsmatrix

done
done
done
done
done
done
done
done
done
done
done
done