[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
NODE_ENV = "production" 