name: "XMTP Test Setup"
description: "Sets up Node.js environment with caching and installs dependencies for XMTP tests"

inputs:
  cache-data:
    description: "Whether to cache .data and .env files"
    required: false
    default: "false"
  test-name:
    description: "Name of the test for notifications and artifact naming"
    required: true
  env:
    description: "Test environment (dev, production, etc.)"
    required: false
    default: "dev"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Prepare Yarn
      run: corepack prepare yarn@4.6.0 --activate
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          .yarn/cache
        key: deps-v2-${{ hashFiles('yarn.lock', 'package.json') }}
        restore-keys: |
          deps-v2-${{ hashFiles('yarn.lock') }}
          deps-v2-

    - name: Cache TypeScript build
      uses: actions/cache@v4
      with:
        path: |
          .tsbuildinfo
          dist
        key: tsc-${{ hashFiles('tsconfig.json', 'package.json', 'yarn.lock') }}-${{ hashFiles('**/*.ts', '!node_modules/**') }}
        restore-keys: |
          tsc-${{ hashFiles('tsconfig.json', 'package.json', 'yarn.lock') }}
          tsc-

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          .playwright-cache
        key: playwright-v2-${{ hashFiles('package.json', 'yarn.lock') }}
        restore-keys: |
          playwright-v2-
          playwright-

    - name: Cache test data
      if: ${{ inputs.cache-data == 'true' || inputs.cache-data == true }}
      uses: actions/cache@v4
      with:
        path: |
          .data
          .env
        key: data-${{ inputs.env }}
        restore-keys: |
          data-${{ inputs.env }}

    - name: Show cache status
      if: ${{ inputs.cache-data == 'true' || inputs.cache-data == true }}
      run: |
        echo "Data caching is ENABLED for .data and .env files"
        echo "Cache key: data-${{ inputs.env }}"
        echo "Environment: ${{ inputs.env }}"
        echo "Test name: ${{ inputs.test-name }}"
      shell: bash

    - name: Install dependencies
      run: yarn
      shell: bash
