name: Agents
description: "should verify performance of the library in the production network"

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [agents-dms, agents-tagged, agents-untagged]
        environment: [dev, production]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.environment }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      DEFAULT_STREAM_TIMEOUT_MS: 20000
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup test environment
        uses: ./.github/actions/xmtp-test-setup

      - name: Run tests
        run: yarn test ${{ matrix.test }} --debug --no-fail

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          status: ${{ job.status }}
          test-name: ${{ matrix.test }}
          environment: ${{ matrix.environment }}
