name: Agents
description: Check that agents answer response is below 9 seconds for a new user. If it fails notify the team.

on:
  schedule:
    - cron: "10 * * * *" # Runs at 10 minutes past each hour
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.environment }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      WALLET_KEY: ${{ secrets.WALLET_KEY }}
      DEFAULT_STREAM_TIMEOUT_MS: 8000
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn retry agents --no-fail
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.environment }}
          path: |
            logs/**/*
            .data/**/*
            .env
          if-no-files-found: ignore
          overwrite: true
          include-hidden-files: true
          retention-days: 90
