name: Browser
description: "verify browser support"

on:
  schedule:
    - cron: "15,45 * * * *" # Runs at 15 and 45 minutes past each hour
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [browser]
        env: [dev, production]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      REGION: ${{ vars.REGION }}
      LOGGING_LEVEL: "off"
      LOG_LEVEL: "info"
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup test env
        uses: ./.github/actions/xmtp-test-setup

      - name: Run tests
        run: yarn test ${{ matrix.test }} --no-fail --env ${{ matrix.env }} # something makes it fail on --debug mode. Not sure what

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        uses: ./.github/actions/slack-notification
        with:
          workflow-name: 'Browser (${{ matrix.test }}, ${{ matrix.env }})'
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
