name: Dms
description: "dms"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [dms]
        environment: [dev]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.environment }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          # Disable built-in cache to use shared cache below
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
          key: deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test ${{ matrix.test }}
      - name: Send Slack notification on failure
        if: failure() || cancelled()
        run: |
          STATUS="${{ job.status == 'cancelled' && 'timed out' || 'failed' }}"
          yarn notify-failure "${{ matrix.test }}" "${{ matrix.environment }}" "${{ github.workflow }}" "$STATUS"
      - name: Upload logs and environment
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-env-${{ matrix.environment }}-${{ matrix.test }}
          path: |
            logs/**/*
            .env
          if-no-files-found: ignore
          overwrite: true
          include-hidden-files: true
          retention-days: 90
      - name: Upload installation databases
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: install-db-${{ matrix.environment }}-${{ matrix.test }}
          path: |
            .data/**/*
          if-no-files-found: ignore
          overwrite: true
          include-hidden-files: true
          retention-days: 90
