name: Forks
description: "Daily forks testing on local network"

on:
  schedule:
    # Run every 12 hours at 2 AM and 2 PM UTC
    - cron: "0 2,14 * * *"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      REGION: ${{ vars.REGION }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      XMTP_ENV: local
    steps:
      - uses: actions/checkout@v4

      - name: Setup test env
        uses: ./.github/actions/xmtp-test-setup
        with:
          test-name: "forks"
          env: "local"
          cache-data: "true"

      - name: Start local XMTP network
        run: ./dev/up

      - name: Wait for network to be ready
        run: sleep 30

      - name: Run forks test
        run: yarn test forks --attempts 50 --env local --log warn --file --forks

      - name: Stop local XMTP network
        if: always()
        run: ./dev/down

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          test-name: "forks"
          env: "local"
          save-to-cache: "true"

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        uses: ./.github/actions/slack-notification
        with:
          workflow-name: "Forks"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
