name: Functional
description: "should verify performance of the library in the dev network"

on:
  schedule:
    - cron: "15 * * * *" # Default schedule for browser tests
    - cron: "45 * * * *" # Default schedule for regression tests
    - cron: "30 * * * *" # Default schedule for agents tests
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test: browser
            schedule: "15 * * * *"
          - test: regression
            schedule: "45 * * * *"
          - test: agents
            schedule: "30 * * * *"
        environment: [production]
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == matrix.schedule
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.environment }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test ${{ matrix.test }} --no-fail --debug
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.environment }}
          path: |
            logs/**/*
            .data/**/*
            .env
          if-no-files-found: ignore
          overwrite: true
          include-hidden-files: true
          retention-days: 90
