name: Functional
description: "should verify message loss when receiving via 200 streams"

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours at 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [functional]
        environment: [dev, production]
    env:
      # MAIN
      LOGGING_LEVEL: "error"
      XMTP_ENV: ${{ matrix.environment }}
      LOG_LEVEL: ""
      # TESTS
      WORKER_COUNT: 5
      BATCH_SIZE: 5
      MAX_GROUP_SIZE: 10
      DELIVERY_AMOUNT: 10
      DELIVERY_RECEIVERS: 4
      # OPTIONAL
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      GEOLOCATION: ${{ vars.GEOLOCATION }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          # Disable built-in cache to use shared cache below
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
          key: deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test ${{ matrix.test }} --debug --no-fail
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.environment }}
          path: |
            logs/**/*
            .data/**/*
          if-no-files-found: ignore
          include-hidden-files: true
          retention-days: 90
