name: Performance
description: "performance "

on:
  #pull_request:
  schedule:
    - cron: "0 * * * *" # Runs every hour at 30 minutes past (30+ min separation from Large at :00)
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [performance]
        size: [5-10-50]
        versions: [3]
        env: [dev, production]
        cache-data: [false]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      REGION: ${{ vars.REGION }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup test env
        uses: ./.github/actions/xmtp-test-setup
        with:
          cache-data: ${{ matrix.cache-data }}
          test-name: ${{ matrix.test }}-${{ matrix.size }}
          env: ${{ matrix.env }}

      - name: Sleep for ${{ matrix.delay_minutes }} minutes
        if: matrix.delay_minutes > 0
        run: sleep $(( ${{ matrix.delay_minutes }} * 60 ))

      - name: Run tests ${{ matrix.size }}
        run: yarn test ${{ matrix.test }} --no-fail --log warn --file --env ${{ matrix.env }} --size ${{ matrix.size }} --versions ${{ matrix.versions }}

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          save-to-cache: ${{ matrix.cache-data }}
          test-name: ${{ matrix.test }}-${{ matrix.size }}
          env: ${{ matrix.env }}

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        uses: ./.github/actions/slack-notification
        with:
          workflow-name: "Performance (${{ matrix.test }}, ${{ matrix.env }}, ${{ matrix.size }})"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
