name: Performance
description: "should verify performance "

on:
  #pull_request:
  schedule:
    - cron: "30 * * * *" # Runs every hour at 30 minutes past (30+ min separation from Large at :00)
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [performance]
        environment: [dev, production]
        BATCH_SIZE: [5-10, 50-100, 150-200]
        cache_data: [false, true]
        include:
          - BATCH_SIZE: 5-10
            delay_minutes: 0
            cache_data: false
          - BATCH_SIZE: 5-10
            delay_minutes: 2
            cache_data: true
          - BATCH_SIZE: 50-100
            delay_minutes: 5
            cache_data: false
          - BATCH_SIZE: 50-100
            delay_minutes: 7
            cache_data: true
          - BATCH_SIZE: 150-200
            delay_minutes: 10
            cache_data: false
          - BATCH_SIZE: 150-200
            delay_minutes: 12
            cache_data: true
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.environment }}
      REGION: ${{ vars.REGION }}
      BATCH_SIZE: ${{ matrix.BATCH_SIZE }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup test environment
        uses: ./.github/actions/xmtp-test-setup
        with:
          cache-data: ${{ matrix.cache_data }}

      - name: Delay execution to spread batch runs
        if: ${{ matrix.delay_minutes > 0 }}
        run: sleep $((${{ matrix.delay_minutes }} * 60))

      - name: Run tests ${{ matrix.BATCH_SIZE }} (cache: ${{ matrix.cache_data }})
        run: yarn test ${{ matrix.test }} --no-fail --debug

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          test-name: ${{ matrix.test }}
          environment: ${{ matrix.environment }}

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        run: yarn workflow-failure "Performance"
