name: Performance
description: "should verify performance "

on:
  #pull_request:
  schedule:
    - cron: "30 * * * *" # Runs every hour at 30 minutes past (30+ min separation from Large at :00)
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [performance]
        env: [dev, production]
        cache-data: [true]
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.env }}
      REGION: ${{ vars.REGION }}
      GH_CACHE: true
      BATCH_SIZE: 5-10-50-100
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup test env
        uses: ./.github/actions/xmtp-test-setup
        with:
          cache-data: ${{ matrix.cache-data }}
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}

      - name: Run tests ${{ matrix.BATCH_SIZE }}
        run: yarn test ${{ matrix.test }} --no-fail --debug

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          save-to-cache: ${{ matrix.cache-data }}
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        run: yarn workflow-failure "Performance"
