name: Performance
description: "verify performance "

on:
  #pull_request:
  schedule:
    - cron: "30 * * * *" # Runs every hour at 30 minutes past (30+ min separation from Large at :00)
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [performance]
        size: [5-10-50, 100-150, 200-250]
        env: [dev, production]
        cache-data: [false]
        include:
          - size: 5-10-50
            delay_minutes: 0
          - size: 100-150
            delay_minutes: 5
          - size: 200-250
            delay_minutes: 15
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      REGION: ${{ vars.REGION }}
      GH_CACHE: true
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup test env
        uses: ./.github/actions/xmtp-test-setup
        with:
          cache-data: ${{ matrix.cache-data }}
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}

      - name: Run tests ${{ matrix.size }}
        run: yarn test ${{ matrix.test }} --no-fail --debug --env ${{ matrix.env }} --size ${{ matrix.size }}

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          save-to-cache: ${{ matrix.cache-data }}
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        run: yarn workflow-failure "Performance"
