name: Validate agents repo

on:
  #pull_request:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  validate:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      REGION: ${{ vars.REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone XMTP agent examples
        run: |
          git clone https://github.com/ephemeraHQ/xmtp-agent-examples.git
          cd xmtp-agent-examples
          yarn install --no-frozen-lockfile
          yarn gen:keys

      - name: Run agent
        run: |
          cd xmtp-agent-examples
          timeout 20s yarn dev | tee output.log
          if grep -q "Waiting for messages..." output.log; then
            echo "Success: Agent started successfully and is waiting for messages"
            exit 0
          else
            echo "Error: Agent did not reach 'Waiting for messages...' state"
            exit 1
          fi

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        uses: ./.github/actions/slack-notification
        with:
          workflow-name: "Validate agents repo"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
