name: Validate agents repo

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  validate:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      XMTP_ENV: ${{ vars.XMTP_ENV }}
      REGION: ${{ vars.REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone XMTP agent examples
        run: |
          git clone https://github.com/ephemeraHQ/xmtp-agent-examples.git
          cd xmtp-agent-examples

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # Disable built-in cache since we're working with external repo

      - name: Install dependencies
        run: |
          cd xmtp-agent-examples
          yarn install

      - name: Generate keys
        run: |
          cd xmtp-agent-examples
          yarn gen:keys
          echo "XMTP_ENV=${{ vars.XMTP_ENV }}" >> .env

      - name: Create .env file
        run: echo "XMTP_ENV=local" > .env

      - name: Run agent
        run: |
          cd xmtp-agent-examples
          timeout 20s yarn dev | tee output.log
          if grep -q "Waiting for messages..." output.log; then
            echo "Success: Agent started successfully and is waiting for messages"
            exit 0
          else
            echo "Error: Agent did not reach 'Waiting for messages...' state"
            exit 1
          fi

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        uses: ./.github/actions/slack-notification
        with:
          workflow-name: 'Validate agents repo'
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
