name: Wildcard
description: "Manual PR verification workflow - supports functional and performance tests"

on:
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [production]
        test: [performance] # cache testing instead of actual tests
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      XMTP_ENV: ${{ matrix.env }}
      LOGGING_LEVEL: error
      LOG_LEVEL: info
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      REGION: ${{ vars.REGION }}
      BATCH_SIZE: 5-10
    steps:
      - uses: actions/checkout@v4

      - name: Setup test env
        uses: ./.github/actions/xmtp-test-setup
        with:
          cache-data: true
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}

      - name: Create test files for cache verification
        run: |
          mkdir -p .data
          echo "Test data created at $(date)" > .data/cache-test-$(date +%s).txt
          echo "Cache test run: ${{ github.run_number }}" >> .data/cache-test-$(date +%s).txt
          echo "Run ID: ${{ github.run_id }}" >> .data/cache-test-$(date +%s).txt

          if [ ! -f ".env" ]; then
            echo "XMTP_ENV=${{ matrix.env }}" > .env
            echo "LOGGING_LEVEL=error" >> .env
          fi

      - name: Run tests
        run: yarn test ${{ matrix.test }}

      - name: Cleanup and upload artifacts
        if: always()
        uses: ./.github/actions/xmtp-test-cleanup
        with:
          test-name: ${{ matrix.test }}
          env: ${{ matrix.env }}
          save-to-cache: true

      - name: Send Slack notification on failure
        if: failure() || cancelled()
        run: yarn workflow-failure "${{ matrix.test }}"
