name: Update XMTP node-sdk and open PR

on:
  schedule:
    - cron: "0 6 * * *" # daily at 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-xmtp-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: |
          yarn --version
          yarn install --immutable || yarn install

      - name: Run update script
        id: update
        run: |
          node version-management/update-sdk.js
        env:
          GITHUB_ACTIONS: true

      - name: Install to update lockfile
        run: |
          yarn install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add latest @xmtp/node-sdk and mapping"
          title: "chore: update @xmtp/node-sdk and VersionList"
          body: |
            Automated update of @xmtp/node-sdk aliases and VersionList.

            This PR was generated by a scheduled workflow.
          branch: chore/update-xmtp-node-sdk
          base: main
          labels: |
            dependencies
            automated-pr
          signoff: false
          delete-branch: true
